stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - src/utils/config.py
      - src/utils/data_fetcher.py
      - src/utils/logger.py
      - src/utils/data_splitter.py
      - src/utils/data_saver.py
    params:
      - data_split.test_size
      - data_split.val_size
      - data_split.random_state
      - data_split.mode
      - data_split.time_series_splits
    outs:
      - data/raw/bike_sharing_data.csv
      - data/interim/X_train.csv
      - data/interim/y_train.csv
      - data/interim/X_val.csv
      - data/interim/y_val.csv
      - data/interim/X_test.csv
      - data/interim/y_test.csv
  data_validation:
    cmd: python src/components/data_validation.py
    deps:
      - src/components/data_validation.py
      - src/utils/config.py
      - src/utils/data_loader.py
      - src/utils/logger.py
      - data/raw/bike_sharing_data.csv
  data_preprocessing:
    cmd: python src/components/data_preprocessing.py
    deps:
      - src/components/data_preprocessing.py
      - src/components/feature_cleaning.py
      - src/components/feature_engineering.py
      - src/components/feature_scaling.py
      - src/utils/config.py
      - src/utils/data_loader.py
      - src/utils/data_saver.py
      - src/utils/logger.py
      - data/interim/X_train.csv
      - data/interim/y_train.csv
      - data/interim/X_val.csv
      - data/interim/y_val.csv
      - data/interim/X_test.csv
      - data/interim/y_test.csv
    params:
      - feature_engineering
    outs:
      - data/processed/X_train_processed.csv
      - data/processed/y_train_transformed.csv
      - data/processed/X_val_processed.csv
      - data/processed/y_val_transformed.csv
      - data/processed/X_test_processed.csv
      - data/processed/y_test_transformed.csv
      - artifacts/pipelines/data_preprocessing_pipeline.pkl
  model_training:
    cmd: python src/components/model_training.py
    deps:
      - src/components/model_training.py
      - src/utils/config.py
      - src/utils/data_loader.py
      - src/utils/logger.py
      - data/processed/X_train_processed.csv
      - data/processed/y_train_transformed.csv
      - data/processed/X_val_processed.csv
      - data/processed/y_val_transformed.csv
    params:
      - model_training
    outs:
      - artifacts/models
  model_evaluation:
    cmd: python src/components/model_evaluation.py
    deps:
      - src/components/model_evaluation.py
      - src/utils/config.py
      - src/utils/data_loader.py
      - src/utils/logger.py
      - artifacts/models
      - data/processed/X_test_processed.csv
      - data/processed/y_test_transformed.csv
    metrics:
      - artifacts/evaluation/evaluation_table.txt:
          cache: false
    plots:
      - artifacts/evaluation/residuals_plot.png:
          cache: false
      - artifacts/evaluation/actual_vs_predicted.png:
          cache: false