# Parameters for the Bike Sharing Demand Prediction project

data_split:
  test_size: 0.15
  val_size: 0.15
  random_state: 42
  mode: random
  time_series_splits: 5

feature_engineering:
  run_vif: False

model_training:
  lgbm:
    n_estimators: [100, 300, 500]
    learning_rate: [0.1, 1.0]
    num_leaves: [20, 31, 40]
  xgb:
    n_estimators: [100, 300, 500]
    learning_rate: [0.1, 1.0]
    max_depth: [3, 5, 7]

prediction:
  model_name: LightGBM_final_model.pkl
